# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    # authors:
    #   - github-actions[bot]

  categories:
    - title: ğŸš§ Breaking Changes ğŸ—
      labels:
        # - Semver-Major
        - breaking-change

    - title: ğŸ‚ New Features ğŸš€
      labels:
        # - Semver-Minor
        - enhancement
        - feature

    - title: ğŸ› Bug Fixes ğŸ› 
      labels:
        # - Semver-Patch
        - bug
        - patch

    - title: ğŸ–¥ Miscellaneous ğŸ“ƒ
      labels:
        - "*"
